# Generated by Django 6.0.4 on 2026-04-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='description',
            new_name='c_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='e_category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='e_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='e_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='event',
            new_name='p_event',
        ),
    ]
