# Generated by Django 6.0.4 on 2026-04-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_description_catagory_c_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='e_category',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='p_event',
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
