# Generated by Django 6.0.4 on 2026-04-18 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_remove_event_e_category_remove_participant_p_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_description', models.TextField()),
                ('e_date', models.DateField()),
                ('e_time', models.TimeField()),
                ('e_location', models.CharField(max_length=100)),
                ('e_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=254, unique=True)),
                ('p_event', models.ManyToManyField(to='events.event')),
            ],
        ),
    ]
