# Generated by Django 6.0.4 on 2026-04-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_category',
            new_name='e_catagory',
        ),
    ]
